<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_help-image</name>
   <tag></tag>
   <elementGuidId>c4db273f-8fdd-4981-a4c1-f65aa11fa0a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.help-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div[2]/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>105c2bf0-7c38-463b-8d28-dc297a1d5ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/HelpImage.80d115c3b9997525131d.png</value>
      <webElementGuid>6ea5b114-ab04-4700-aec2-2ee0334382db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Help</value>
      <webElementGuid>039db737-eafb-4055-90ab-e58ee7483351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-image</value>
      <webElementGuid>d44ca482-20d4-4834-abe3-629f25adf4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>13706b77-a13a-4798-bea5-652781208c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30px</value>
      <webElementGuid>a429f4e5-1f78-4067-9186-ef013af4ad14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container inner-wrapper&quot;]/div[@class=&quot;mt-2&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col-md-5&quot;]/img[@class=&quot;help-image&quot;]</value>
      <webElementGuid>9a11f3a0-a31a-40a3-9cf1-e998fb0775e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/img[2]</value>
      <webElementGuid>dcf49961-8030-421e-a554-0e121704b8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Help']</value>
      <webElementGuid>3a56eb25-3bd5-4168-8c8c-928a3406c01b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>7cece3d3-5dd5-4b91-90e5-8258a5fab5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/HelpImage.80d115c3b9997525131d.png' and @alt = 'Help']</value>
      <webElementGuid>0c1abbae-9efd-4d9c-b435-b05e98ebe8f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
